//Generated by .NET Class Generator Tools

using APP.Capture.Domain;
using System.Data;
using System.Data.SqlClient;
using APP.Framework.Infrastructure;

namespace APP.Capture.Infrastructure
{
	public partial class CaptureMobileDataAccess
	{

	}
}
