using APP.Framework.Domain;

using System;

using System.Diagnostics;

/*Generated by .NET Class Generator Tools*/

namespace APP.Camera.Domain
{
    [DebuggerStepThrough()]
    public partial class MsUserRole : AbstractTable
    {
        #region Data Member
        private string _moduleid;
        private string _userroleid;
        private string _userroledesc;
        private string _crtusrid;
        private DateTime _tscrt;
        private string _modusrid;
        private DateTime? _tsmod;
        private string _activeflag = "Y";
        #endregion

        #region Default Value
        public MsUserRole()
        {
        }
        #endregion


        #region Properties
        public string ModuleID
        {
            get
            {
                return _moduleid;
            }
            set
            {
                _moduleid = value;
                Modify();
            }
        }

        public string UserRoleID
        {
            get
            {
                return _userroleid;
            }
            set
            {
                _userroleid = value;
                Modify();
            }
        }

        public string UserRoleDesc
        {
            get
            {
                return _userroledesc;
            }
            set
            {
                _userroledesc = value;
                Modify();
            }
        }

        public string CrtUsrID
        {
            get
            {
                return _crtusrid;
            }
            set
            {
                _crtusrid = value;
                Modify();
            }
        }

        public DateTime TsCrt
        {
            get
            {
                return _tscrt;
            }
            set
            {
                _tscrt = value;
                Modify();
            }
        }

        public string ModUsrID
        {
            get
            {
                return _modusrid;
            }
            set
            {
                _modusrid = value;
                Modify();
            }
        }

        public DateTime? TsMod
        {
            get
            {
                return _tsmod;
            }
            set
            {
                _tsmod = value;
                Modify();
            }
        }

        public string ActiveFlag
        {
            get
            {
                return _activeflag;
            }
            set
            {
                _activeflag = value;
                Modify();
            }
        }

        #endregion

    }
}