//Generated by .NET Class Generator Tools

using APP.Capture.Domain;
using APP.Capture.Infrastructure;
using APP.Framework.Application;

using APP.Framework.Infrastructure;

using System;

using System.Diagnostics;

namespace APP.Capture.Application
{
	[Serializable()]
	public partial class CaptureMobileAppService


	{

	}
}
